# Generated by Django 4.1.5 on 2023-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.IntegerField(default=0)),
                ('videos', models.IntegerField(default=0)),
                ('pdf', models.IntegerField(default=0)),
            ],
        ),
    ]
