# Generated by Django 4.1.5 on 2023-01-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='videos',
            new_name='video',
        ),
    ]
