# Generated by Django 4.1.5 on 2023-01-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_comments_stats_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='pdf',
            new_name='pdfs',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='video',
            new_name='videos',
        ),
    ]
