# Generated by Django 4.1.5 on 2023-01-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_comment_stats_comments_rename_pdf_stats_pdfs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
