# Generated by Django 4.1.7 on 2023-02-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_comment_date_alter_pdf_date_alter_video_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
